version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  heroku:
    build: .
    command: 'bash -c ''mix phoenix.server'''
    dockerfile: Dockerfile.heroku
    working_directory: /app/user
    environment:
      LANG: en_US.UTF-8
      HOST: localhost
      PORT: 4000
      # DATABASE_URL: 'postgres://db:@db:4000/api_prod'
    ports:
      - '4000:4000'
    depends_on:
      - db

